### ISSUE TITLE
Commit message tidak sesuai

### ISSUE THREAD

**Issue by anyrta7** [honestyan/malas-commit#4]
![Screenshot from 2024-10-10 21-47-03](https://github.com/user-attachments/assets/35d40399-4c60-4cde-9d7c-c026e0999db1)
Ini saya diprojek laravel tapi commitnya malah mengarah  ke projek golang, dan saya sama sekali tidak punya projek golang. Fix lagi bang, sebelum update ini berjalan lancar banget dan membantu, tapi setelah update commit message saya jadi berantakan wkwkwkw

**Comment by honestyan** [comment]
thanks feedbacknya @anyrta7 , gonna check later ya.

**Comment by honestyan** [comment]
kalo di-generate ulang apakah masi sama? @anyrta7

**Comment by anyrta7** [comment]
iya masih, malah kadang makin ngaco bang. tapi ga selalu gitu, cm beberapa yang ngaco message-nya

**Comment by honestyan** [comment]
Hi @anyrta7,

Thanks again for reporting this issue! I've taken a closer look and made some adjustments to the commit message generation logic.

The fix has been applied in the latest commit: [ce25c42](https://github.com/honestyan/malas-commit/commit/ce25c423d918488fa58d925e8904c2daec64b40f).

Please try updating to the latest version and let me know if the issue persists. I believe this should resolve the commit message mismatch.

You can run this command below if you had installed already.
```
npm update malas-commit -g
```

Thanks for your patience, and feel free to reopen this issue if needed!

Closing this for now.

Best,  
@honestyan
